require('user.options')
require('user.keymaps')
require('user.plugins')

-- Plugin configuration
require('user.catppuccin')
require('user.indent-blankline')
require('user.lualine')
require('user.gitsigns')
require('user.comment')
require('user.colorizer')
require('user.cmp')
require('user.treesitter')
require('user.mason')
require('user.lsp-config')
require('user.friendly-snippets')
require('user.codeium')
-- require('user.chatgpt')
